---
- hosts: all
  user: root
  become: yes
  roles:
    - {role: common, tags: always}
    - {role: victoriametrics, tags: victoriametrics,deploy}
    - {role: prometheus, tags: prometheus,deploy}
    - {role: node-exporter, tags: node-exporter,deploy}
    - {role: down, tags: down}