---
- hosts: all
  user: root
  become: yes
  roles:
    - {role: common, tags: always}
    - {role: victoriametrics, tags: deploy}
    - {role: prometheus, tags: deploy}
    - {role: node-exporter, tags: deploy}
    - {role: down, tags: down}