---

- name: Down victoriametrics docker-compose
  shell: docker-compose --compatibility -f {{API_CONFIGURATION_PATH}}/victoriametrics/docker-compose.victoriametrics.yml down -v
  tags: down

- name: Down prometheus docker-compose
  shell: docker-compose --compatibility -f {{API_CONFIGURATION_PATH}}/prometheus/docker-compose.prometheus.yml down -v
  tags: down

- name: Stop Node Exporter
  shell: docker stop node-exporter && docker rm node-exporter
  tags: down