---
- set_fact:
    role_name: prometheus

- name: Open 9090 port in iptables for Prometheus monitor server
  iptables:
    chain: INPUT
    protocol: tcp
    source: 0.0.0.0
    destination_port: 9090
    jump: ACCEPT
    action: insert
    comment: "ALLOW CONNECT FROM PROMETHEUS MONITOR SERVER "

- name: Persisten iptables rule
  shell: iptables-save > /etc/iptables/rules.v4
  ignore_errors: yes
  tags:
    - node-exporter

- name: create folder data for {{role_name}}
  file: 
    path: "{{DATA_DIR}}/{{role_name}}" 
    state: directory 
    recurse: yes 
    owner: root
    group: root


- name: create folder config for {{role_name}}
  file: 
    path: "{{API_CONFIGURATION_PATH}}/{{role_name}}/config" 
    state: directory 
    recurse: yes 
    owner: root
    group: root

- name: copy docker-compose file
  template:
    src: docker-compose.prometheus.yml.j2
    dest: "{{API_CONFIGURATION_PATH}}/{{role_name}}/docker-compose.prometheus.yml"

- name: copy config file
  template:
    src: prometheus.yaml.j2
    dest: "{{API_CONFIGURATION_PATH}}/{{role_name}}/config/prometheus.yml"

- name: create folder config for {{role_name}} rules
  file: 
    path: "{{API_CONFIGURATION_PATH}}/{{role_name}}/rules" 
    state: directory 
    recurse: yes 
    owner: root
    group: root

- name: copy docker-compose file
  template:
    src: rules/rule.yml.j2
    dest: "{{API_CONFIGURATION_PATH}}/{{role_name}}/rules/rule.yml"

- name: docker-compose pull
  shell: docker-compose --compatibility -f {{API_CONFIGURATION_PATH}}/{{role_name}}/docker-compose.prometheus.yml pull

- name: docker-compose stop old container
  shell: docker-compose --compatibility -f {{API_CONFIGURATION_PATH}}/{{role_name}}/docker-compose.prometheus.yml stop

- name: docker-compose remove old container
  shell: docker-compose --compatibility -f {{API_CONFIGURATION_PATH}}/{{role_name}}/docker-compose.prometheus.yml rm -f

- name: Start {{ role_name }} docker-compose
  shell: docker-compose --compatibility -f {{API_CONFIGURATION_PATH}}/{{role_name}}/docker-compose.prometheus.yml up -d
  when: service_docker_status.rc == 0