---

- name: Check if docker is running
  shell: ps aux | grep dockerd | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_docker_status

- name: Check if pip is installed
  shell: python3 --version
  ignore_errors: yes
  register: python3_version

- name: Check if pip is installed
  shell: pip3 -V
  ignore_errors: yes
  register: pip_version

- name: Check if jq is installed
  shell: jq -V
  ignore_errors: yes
  register: jq_version

- name: Check if docker is installed
  shell: docker -v
  ignore_errors: yes
  register: docker_py_version

- name: Check if docker-compose is installed
  shell: docker-compose -v
  ignore_errors: yes
  register: docker_compose_version

- name: Install python3
  shell: apt-get update && apt install python3.8 -y
  when: python3_version.rc != 0

- name: Install python-pip and jq if not exists
  shell: apt-get update && apt-get -y install python3-pip && apt-get install -y jq
  when: pip_version.rc != 0 or jq_version.rc != 0

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  when: docker_py_version.rc != 0

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  when: docker_py_version.rc != 0

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_py_version.rc != 0

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    update_cache: yes
    state: present
  when: docker_py_version.rc != 0

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  when: docker_py_version.rc != 0

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: docker_py_version.rc != 0

- name: assicurati che docker sia attivo
  service:
    name: docker
    state: started
    enabled: yes
  when: docker_py_version.rc != 0

- name: Add remote "ubuntu" user to "docker" group
  remote_user: ubuntu
  user:
    name: "ubuntu"
    group: "docker"
    append: yes
  tags:
    - docker
  when: docker_py_version.rc != 0

- name: Install docker-compose
  remote_user: ubuntu
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  when: docker_compose_version.rc != 0